### ISSUE TITLE
个人看法

### ISSUE THREAD

**Issue by wulongwang** [shenAlexy/AvatarGroupImage#1]
- (UIImageView *)avtarGroupOnImageView:(UIImageView *)canvasImageView subImageViews:(NSArray *)imageViews marginValue:(CGFloat)marginValue{

这个方法的实现，那个if ,这里可以直接根据图片的个数动态计算效果更好，就省去if判断代码更加简洁，
还有一点就是 在实际应用过程中，qq群组的头像方式应用得更多。根据头像的url 画出群组头像。

**Comment by shenAlexy** [comment]
嗯嗯，谢谢你的建议，后续我会修改的，谢谢谢谢
