### ISSUE TITLE
你能写钉钉的那个通讯录吗？

### ISSUE THREAD

**Issue by liujieyuu** [shenAlexy/AvatarGroupImage#2]
你能写钉钉的那个通讯录吗？

**Comment by shenAlexy** [comment]
我之前写了一个微信的通讯录:WechatContacts，你可以参考下

**Comment by liujieyuu** [comment]
现在我遇到一个问题，需要高仿钉钉的那个通讯录，尼这个我会写的，需求就是服务器那边配置部门，人员，手机端获取数据，进行展示，部门下面可能会有很多部门、分组，然后才是人员，所以，层级不确定

**Comment by shenAlexy** [comment]
就是一个树型结构，获取指定节点数据？

**Comment by shenAlexy** [comment]
树型json数据解析，获取某节点数据！

在 2016年4月13日 下午5:11，liujieyuu notifications@github.com写道：
